# Generated by Django 4.2 on 2026-07-09 12:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('foto_profil', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profil/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_customer', models.CharField(max_length=255, verbose_name='Nama Customer')),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tanggal_bergabung', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Bergabung')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Master Customer',
                'ordering': ['nama_customer'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='profile/default.png', upload_to='profile/')),
                ('jabatan', models.CharField(default='Administrator', max_length=100)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Upload',
                'verbose_name_plural': 'Riwayat Upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Permintaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis_label', models.CharField(max_length=100)),
                ('jenis_kemasan', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(default=0)),
                ('nilai', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frekuensi', models.IntegerField(default=1)),
                ('total_nilai', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permintaans', to='core.customer')),
            ],
            options={
                'verbose_name': 'Permintaan',
                'verbose_name_plural': 'Riwayat Permintaan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='HasilClustering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('tanggal_clustering', models.DateTimeField(auto_now_add=True)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusterings', to='core.customer')),
            ],
            options={
                'verbose_name': 'Hasil Clustering',
                'verbose_name_plural': 'Riwayat Clustering',
                'ordering': ['-tanggal_clustering'],
            },
        ),
    ]
