# Generated by Django 4.2 on 2026-07-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_alamat_customuser_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_profil',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profil/'),
        ),
    ]
