# Generated by Django 4.2 on 2026-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_omzet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_qty',
            field=models.FloatField(default=0),
        ),
    ]
