# Generated by Django 4.2 on 2026-08-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_area_customer_total_omzet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50, unique=True)),
                ('nama_barang', models.CharField(max_length=255)),
                ('satuan', models.CharField(default='pcs', max_length=50)),
                ('metode', models.CharField(choices=[('FIFO', 'FIFO (First In First Out)'), ('LIFO', 'LIFO (Last In First Out)')], default='FIFO', max_length=10)),
                ('stok_total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Barang',
                'verbose_name_plural': 'Master Barang',
                'ordering': ['nama_barang'],
            },
        ),
        migrations.CreateModel(
            name='KategoriBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori Barang',
                'verbose_name_plural': 'Kategori Barang',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('MASUK', 'Barang Masuk'), ('KELUAR', 'Barang Keluar')], max_length=10)),
                ('qty', models.FloatField()),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('referensi', models.CharField(blank=True, help_text='Contoh: No Order / Nama Customer', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksis', to='core.barang')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaksi Barang',
                'verbose_name_plural': 'Riwayat Transaksi Barang',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField()),
                ('qty_masuk', models.FloatField()),
                ('qty_keluar', models.FloatField(default=0)),
                ('sisa', models.FloatField()),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.barang')),
            ],
            options={
                'verbose_name': 'Batch Barang',
                'verbose_name_plural': 'Batch Barang',
                'ordering': ['tanggal_masuk', 'id'],
            },
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barangs', to='core.kategoribarang'),
        ),
    ]
