# Generated by Django 4.2 on 2026-08-24 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_barang_kategoribarang_transaksibarang_batchbarang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kemasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kemasan', models.CharField(max_length=50, unique=True)),
                ('nama_kemasan', models.CharField(max_length=255)),
                ('kapasitas', models.FloatField(blank=True, help_text='Contoh: 25 (untuk kemasan 25 kg)', null=True)),
                ('satuan_kapasitas', models.CharField(default='kg', max_length=20)),
                ('satuan', models.CharField(default='pcs', max_length=30)),
                ('metode', models.CharField(choices=[('FIFO', 'FIFO (First In First Out)'), ('LIFO', 'LIFO (Last In First Out)')], default='FIFO', max_length=10)),
                ('stok_total', models.FloatField(default=0)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Kemasan',
                'verbose_name_plural': 'Master Kemasan',
                'ordering': ['nama_kemasan'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_label', models.CharField(max_length=50, unique=True)),
                ('nama_label', models.CharField(max_length=255)),
                ('gramasi', models.CharField(blank=True, help_text='Contoh: 50g, 100g, 1kg', max_length=50, null=True)),
                ('satuan', models.CharField(default='pcs', max_length=30)),
                ('metode', models.CharField(choices=[('FIFO', 'FIFO (First In First Out)'), ('LIFO', 'LIFO (Last In First Out)')], default='FIFO', max_length=10)),
                ('stok_total', models.FloatField(default=0)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Label',
                'verbose_name_plural': 'Master Label',
                'ordering': ['nama_label'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('MASUK', 'Masuk'), ('KELUAR', 'Keluar')], max_length=10)),
                ('qty', models.FloatField()),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('referensi', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksis', to='core.label')),
            ],
            options={
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiKemasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('MASUK', 'Masuk'), ('KELUAR', 'Keluar')], max_length=10)),
                ('qty', models.FloatField()),
                ('tanggal', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('referensi', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kemasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksis', to='core.kemasan')),
            ],
            options={
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StokOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stok Opname',
                'verbose_name_plural': 'Stok Opname',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JalurIstimewa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pakai_label_ganda', models.BooleanField(default=False, help_text='Pakai label asli + label perusahaan')),
                ('ukuran_kemasan', models.FloatField(blank=True, help_text='Contoh: 25 (kg)', null=True)),
                ('qc_extra', models.BooleanField(default=False)),
                ('pakai_palet', models.BooleanField(default=False)),
                ('diikat', models.BooleanField(default=False)),
                ('relabel', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True, help_text='Catatan khusus untuk gudang', null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jalur_istimewa', to='core.customer')),
                ('kemasan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kemasan')),
                ('label_asli', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.label')),
                ('label_perusahaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.label')),
            ],
            options={
                'verbose_name': 'Jalur Istimewa',
                'verbose_name_plural': 'Jalur Istimewa',
            },
        ),
        migrations.CreateModel(
            name='DetailStokOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_sistem', models.FloatField()),
                ('stok_fisik', models.FloatField()),
                ('selisih', models.FloatField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barang')),
                ('opname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.stokopname')),
            ],
            options={
                'verbose_name': 'Detail Stok Opname',
                'verbose_name_plural': 'Detail Stok Opname',
            },
        ),
        migrations.CreateModel(
            name='BatchLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField()),
                ('qty_masuk', models.FloatField()),
                ('qty_keluar', models.FloatField(default=0)),
                ('sisa', models.FloatField()),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.label')),
            ],
            options={
                'ordering': ['tanggal_masuk', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BatchKemasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateField()),
                ('qty_masuk', models.FloatField()),
                ('qty_keluar', models.FloatField(default=0)),
                ('sisa', models.FloatField()),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kemasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.kemasan')),
            ],
            options={
                'ordering': ['tanggal_masuk', 'id'],
            },
        ),
    ]
