# Generated by Django 4.2 on 2026-08-26 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kemasan_label_transaksilabel_transaksikemasan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.IntegerField()),
                ('label_name', models.CharField(blank=True, max_length=100)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('avg_monetary', models.FloatField(default=0)),
                ('avg_frequency', models.FloatField(default=0)),
                ('avg_recency', models.FloatField(default=0)),
                ('top_products', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('color', models.CharField(default='#0ea5e9', max_length=20)),
            ],
            options={
                'verbose_name': 'Detail Cluster',
                'verbose_name_plural': 'Detail Cluster',
                'ordering': ['cluster_label'],
            },
        ),
        migrations.AlterModelOptions(
            name='hasilclustering',
            options={'ordering': ['-tanggal_clustering'], 'verbose_name': 'Hasil Clustering', 'verbose_name_plural': 'Hasil Clustering'},
        ),
        migrations.CreateModel(
            name='ClusterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('monetary', models.FloatField(default=0)),
                ('frequency', models.FloatField(default=0)),
                ('recency', models.FloatField(default=0)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.clusterdetail')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='core.customer')),
            ],
            options={
                'verbose_name': 'Member Cluster',
                'verbose_name_plural': 'Member Cluster',
                'ordering': ['-monetary'],
            },
        ),
        migrations.CreateModel(
            name='ClusteringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_data', models.PositiveIntegerField(default=0)),
                ('n_clusters', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('processing', 'Sedang Diproses'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('algorithm', models.CharField(default='K-Means', max_length=50)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clustering_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History Clustering',
                'verbose_name_plural': 'History Clustering',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clusterdetail',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='core.clusteringhistory'),
        ),
        migrations.AddField(
            model_name='hasilclustering',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasil_customers', to='core.clusteringhistory'),
        ),
        migrations.AlterUniqueTogether(
            name='clusterdetail',
            unique_together={('history', 'cluster_label')},
        ),
    ]
