# Generated by Django 4.2 on 2026-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clusterdetail_alter_hasilclustering_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchbarang',
            name='tanggal_expired',
            field=models.DateField(blank=True, help_text='Tanggal kadaluarsa batch', null=True),
        ),
    ]
