# Generated by Django 4.2 on 2026-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_batchbarang_tanggal_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='stok_minimum',
            field=models.FloatField(default=0, help_text='Batas stok minimum untuk peringatan'),
        ),
        migrations.AddField(
            model_name='batchlabel',
            name='stok_minimum',
            field=models.FloatField(default=0, help_text='Batas stok minimum untuk peringatan'),
        ),
        migrations.AddField(
            model_name='kemasan',
            name='stok_minimum',
            field=models.FloatField(default=0, help_text='Batas stok minimum untuk peringatan'),
        ),
        migrations.AddField(
            model_name='label',
            name='stok_minimum',
            field=models.FloatField(default=0, help_text='Batas stok minimum untuk peringatan'),
        ),
    ]
