# Generated by Django 4.2 on 2026-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_barang_stok_minimum_batchlabel_stok_minimum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GUDANG', 'Gudang'), ('SALES', 'Sales')], default='ADMIN', max_length=20),
        ),
    ]
